import { TransactionResource, TransactionType, TransactionStatus } from "@/types/transaction.type";
export const demoTransactions: TransactionResource[] = [
  {
    id: "t1",
    campaignId: "c1",
    type: TransactionType.INCOME,
    amount: 5000000,
    date: "2025-09-01T10:00:00Z",
    description: "Quyên góp từ doanh nghiệp XYZ",
    source: "Chuyển khoản ngân hàng",
    receipt: "https://example.com/receipt1.pdf",
    approvedBy: "admin1",
    status: TransactionStatus.APPROVED,
    note: "Đã kiểm tra hóa đơn",
  },
  {
    id: "t2",
    campaignId: "c1",
    type: TransactionType.EXPENSE,
    amount: -1500000,
    date: "2025-09-05T14:30:00Z",
    description: "Mua vật liệu xây dựng",
    source: "Tiền mặt",
    receipt: "https://example.com/receipt2.jpg",
    approvedBy: "admin2",
    status: TransactionStatus.APPROVED,
  },
  {
    id: "t3",
    campaignId: "c1",
    type: TransactionType.INCOME,
    amount: 2000000,
    date: "2025-09-10T09:00:00Z",
    description: "Quyên góp từ cộng đồng",
    source: "Momo wallet",
    status: TransactionStatus.PENDING,
    note: "Chờ xác nhận",
  },
  {
    id: "t4",
    campaignId: "c1",
    type: TransactionType.EXPENSE,
    amount: -800000,
    date: "2025-09-15T16:00:00Z",
    description: "Chi phí di chuyển",
    source: "Tiền mặt",
    receipt: "https://example.com/receipt4.jpg",
    approvedBy: "admin1",
    status: TransactionStatus.REJECTED,
    note: "Hóa đơn không hợp lệ",
  },
];