// src/data/demoVolunteers.ts
import { VolunteerResource, VolunteerStatus, VolunteerRole } from "@/types/volunteer.type";

export const demoVolunteers: VolunteerResource[] = [
  {
    id: "v1",
    full_name: "Nguyễn Văn An",
    email: "an.nguyen@example.com",
    phone: "0901234567",
    avatar: "https://example.com/avatar1.jpg",
    status: VolunteerStatus.APPROVED,
    role: VolunteerRole.COORDINATOR,
    joinedAt: "2025-01-15T10:00:00Z",
    lastActive: "2025-12-10T14:30:00Z",
    campaigns: [
      {
        campaignId: "c1",
        campaignTitle: "Trung Thu Ấm Áp 2025",
        joinedAt: "2025-08-01",
        sessionsAttended: 5,
        pointsEarned: 250,
      },
      {
        campaignId: "c2",
        campaignTitle: "Xanh Hóa Đồi Núi 2025",
        joinedAt: "2025-11-01",
        sessionsAttended: 3,
        pointsEarned: 150,
      },
    ],
    points: 400,
    adminNote: "Tích cực, có kinh nghiệm lãnh đạo nhóm",
  },
  {
    id: "v2",
    fullName: "Trần Thị Bình",
    email: "binh.tran@example.com",
    phone: "0912345678",
    avatar: "",
    status: VolunteerStatus.PENDING,
    role: VolunteerRole.VOLUNTEER,
    joinedAt: "2025-11-20T09:00:00Z",
    campaigns: [],
    points: 0,
    adminNote: "Đang chờ duyệt hồ sơ",
  },
  {
    id: "v3",
    fullName: "Lê Văn Cường",
    email: "cuong.le@example.com",
    phone: "0923456789",
    avatar: "",
    status: VolunteerStatus.LOCKED,
    role: VolunteerRole.VOLUNTEER,
    joinedAt: "2025-05-10T11:00:00Z",
    lastActive: "2025-08-15T16:00:00Z",
    campaigns: [
      {
        campaignId: "c1",
        campaignTitle: "Trung Thu Ấm Áp 2025",
        joinedAt: "2025-08-10",
        sessionsAttended: 2,
        pointsEarned: 100,
      },
    ],
    points: 100,
    adminNote: "Tài khoản bị khóa do vi phạm quy định",
  },
  {
    id: "v4",
    fullName: "Phạm Thị Dung",
    email: "dung.pham@example.com",
    phone: "0934567890",
    avatar: "",
    status: VolunteerStatus.REJECTED,
    role: VolunteerRole.VOLUNTEER,
    joinedAt: "2025-10-05T13:00:00Z",
    campaigns: [],
    points: 0,
    adminNote: "Từ chối do hồ sơ không đủ điều kiện",
  },
  {
    id: "v5",
    fullName: "Hoàng Văn Em",
    email: "em.hoang@example.com",
    phone: "0945678901",
    avatar: "",
    status: VolunteerStatus.PENDING,
    role: VolunteerRole.LEADER,
    joinedAt: "2025-12-01T15:00:00Z",
    campaigns: [],
    points: 0,
    adminNote: "Ứng viên trưởng nhóm, đang chờ phỏng vấn",
  },
];